
/*
 * AboutDialog.java
 *
 * Created on May 3, 2012, 2:46:06 AM
 */
package com.dobydigital.dobixchange.forms;

import com.dobydigital.dobixchange.server.DobiXchangeServer;
import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author XaeroDegreaz
 */
public class AboutDialog extends javax.swing.JDialog {

	/** Creates new form AboutDialog */
	public AboutDialog( java.awt.Frame parent, boolean modal ) {
		super( parent, modal );
		initComponents();
		// Get the size of the screen
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
 
		// Determine the new location of the window
		int w = getSize().width;
		int h = getSize().height;
		int x = (dim.width-w)/2;
		int y = (dim.height-h)/2;
 
		// Move the window
		setLocation(x, y);
		
		this.setIconImage( DobiXchangeServer.instance.imageIcon.getImage() );
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("About DobiXchange Server");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/dobydigital/dobixchange/resources/logoLarge.png"))); // NOI18N

        jTextPane1.setEditable(false);
        jTextPane1.setText("DobiXchange Server is the open-source, server component for DobiXchange, an Android application that allows users to send images from their Android device straight to their computers, and open it directly inside Photoshop.\n\nThe server then monitors for changes to the images, and syncs them immediately back to the device over TCP. This project utilizes the extensible socket server technology provided by SmartSocket 2.1.0, another project of mine on Github.\n\nAuthor: Jerome Doby (Xaero Degreaz)\nSmartSocket: http://www.smartsocket.net\nDoby Digital: http://www.dobydigital.com\nGithub: https://github.com/XaeroDegreaz\n\nSource licensed under MPL 1.1/LGPL 2.1/GPL 2.0");
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 278, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	/**
	 * @param args the command line arguments
	 */
	public static void main( String args[] ) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
//		try {
//			for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
//				if ( "Nimbus".equals( info.getName() ) ) {
//					javax.swing.UIManager.setLookAndFeel( info.getClassName() );
//					break;
//				}
//			}
//		} catch (ClassNotFoundException ex) {
//			java.util.logging.Logger.getLogger( AboutDialog.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//		} catch (InstantiationException ex) {
//			java.util.logging.Logger.getLogger( AboutDialog.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//		} catch (IllegalAccessException ex) {
//			java.util.logging.Logger.getLogger( AboutDialog.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//			java.util.logging.Logger.getLogger( AboutDialog.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//		}
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater( new Runnable() {

			@Override
			public void run() {
				final AboutDialog dialog = new AboutDialog( new javax.swing.JFrame(), true );
				dialog.addWindowListener( new java.awt.event.WindowAdapter() {

					@Override
					public void windowClosing( java.awt.event.WindowEvent e ) {
						dialog.dispose();
					}
				} );
				dialog.setVisible( true );
			}
		} );
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
