
/*
 * SettingsForm.java
 *
 * Created on Apr 5, 2012, 6:58:23 PM
 */
package com.dobydigital.dobixchange.forms;

import com.dobydigital.dobixchange.server.DobiXchangeServer;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author XaeroDegreaz
 */
public class SettingsForm extends javax.swing.JFrame {

	/** Creates new form SettingsForm */
	public SettingsForm() {
		initComponents();
		// Get the size of the screen
		Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
 
		// Determine the new location of the window
		int w = getSize().width;
		int h = getSize().height;
		int x = (dim.width-w)/2;
		int y = (dim.height-h)/2;
 
		// Move the window
		setLocation(x, y);
		
		try {
			txtPhotoshop.setText( DobiXchangeServer.configuration.get( "photoshop" ).getAsString() ); 
			txtHome.setText( DobiXchangeServer.configuration.get( "home" ).getAsString() );
		}catch(Exception e) {
			//# Config prolly not set.
		}
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBrowseHome = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtPhotoshop = new javax.swing.JTextField();
        txtHome = new javax.swing.JTextField();
        btnBrowsePhotoshop = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        btnBrowseHome.setText("Browse...");
        btnBrowseHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseHomeActionPerformed(evt);
            }
        });

        jLabel1.setText("Path to Photoshop.exe");

        jLabel2.setText("Path to preferred home directory (files will save here)");

        txtPhotoshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhotoshopActionPerformed(evt);
            }
        });

        btnBrowsePhotoshop.setText("Browse...");
        btnBrowsePhotoshop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowsePhotoshopActionPerformed(evt);
            }
        });

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(194, 194, 194))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtHome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                            .addComponent(txtPhotoshop, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnBrowseHome)
                            .addComponent(btnBrowsePhotoshop)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSave)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPhotoshop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowsePhotoshop))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBrowseHome))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSave)
                .addContainerGap(163, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void btnBrowsePhotoshopActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_btnBrowsePhotoshopActionPerformed
		FileFilter filter = new FileFilter() {

			@Override
			public boolean accept( File f ) {
				if(f.getName().equalsIgnoreCase( "photoshop.exe" ) || f.isDirectory() ) {
					return true;
				}
				return false;
			}

			@Override
			public String getDescription() {
				return null;
			}
		};
		
		JFileChooser chooser = new JFileChooser( "C:\\Program Files\\" );
		chooser.setFileFilter( filter );
		
		int choice = chooser.showDialog( this, "Select");
		
		if(choice == JFileChooser.APPROVE_OPTION) {
			txtPhotoshop.setText( chooser.getSelectedFile().getAbsolutePath() );
		}
	}//GEN-LAST:event_btnBrowsePhotoshopActionPerformed

	private void txtPhotoshopActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_txtPhotoshopActionPerformed
		// TODO add your handling code here:
	}//GEN-LAST:event_txtPhotoshopActionPerformed

	private void btnBrowseHomeActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_btnBrowseHomeActionPerformed
		JFileChooser chooser = new JFileChooser(  );
		chooser.setFileSelectionMode( JFileChooser.DIRECTORIES_ONLY );
		int choice = chooser.showDialog( this, "Select");
		
		if(choice == JFileChooser.APPROVE_OPTION) {
			txtHome.setText( chooser.getSelectedFile().getAbsolutePath() );
		}
	}//GEN-LAST:event_btnBrowseHomeActionPerformed

	private void btnSaveActionPerformed( java.awt.event.ActionEvent evt ) {//GEN-FIRST:event_btnSaveActionPerformed
		DobiXchangeServer.configuration.addProperty( "photoshop", txtPhotoshop.getText());
		DobiXchangeServer.configuration.addProperty( "home", txtHome.getText());
		
		try {
			FileOutputStream out = new FileOutputStream( "config-dobixchange.json" );
			out.write( DobiXchangeServer.configuration.toString().getBytes() );
			out.close();
			dispose();
		}catch(Exception e) {
			
		}
	}//GEN-LAST:event_btnSaveActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main( String args[] ) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
		 * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
//		try {
//			for ( javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels() ) {
//				if ( "Nimbus".equals( info.getName() ) ) {
//					javax.swing.UIManager.setLookAndFeel( info.getClassName() );
//					break;
//				}
//			}
//		} catch (ClassNotFoundException ex) {
//			java.util.logging.Logger.getLogger( SettingsForm.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//		} catch (InstantiationException ex) {
//			java.util.logging.Logger.getLogger( SettingsForm.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//		} catch (IllegalAccessException ex) {
//			java.util.logging.Logger.getLogger( SettingsForm.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
//			java.util.logging.Logger.getLogger( SettingsForm.class.getName() ).log( java.util.logging.Level.SEVERE, null, ex );
//		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater( new Runnable() {

			public void run() {
				new SettingsForm().setVisible( true );
			}
		} );
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowseHome;
    private javax.swing.JButton btnBrowsePhotoshop;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtHome;
    private javax.swing.JTextField txtPhotoshop;
    // End of variables declaration//GEN-END:variables
}
